# Generated by Django 3.1.1 on 2020-09-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
