# Generated by Django 3.1.1 on 2020-09-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200923_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
