# Generated by Django 3.1.1 on 2020-09-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200924_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='associate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='lead',
            field=models.CharField(default='', max_length=100),
        ),
    ]
